import Head from 'next/head'
import Image from 'next/image'
import Quiz from '@/components/Quiz'
// import the quizcontext provider
import { QuizProvider } from '@/contexts/QuizContext'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <QuizProvider>
          <Quiz />
        </QuizProvider>
      </main>
    </>
  )
}
